### ISSUE TITLE
Invalid selector result

### ISSUE THREAD

**Issue by ar2r13** [csstools/postcss-custom-selectors#44]
```css
@custom-selector :--input input, ::slotted(input);

:--input:focus { ~ }
```

Expected: 
```css
input:focus, ::slotted(input:focus) { ~ }
```

Result:
```css
input:focus, ::slotted(input):focus { ~ }
```
